name: CI - Unit Test

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Restore local tools
        run: dotnet tool restore

      - name: Build (fail on warnings)
        run: dotnet build --no-restore -warnaserror

      - name: Test
        run: dotnet test ./CurrencyExchange.sln --no-build
